//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanksDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int ID { get; set; }
        public int FKBankID { get; set; }
        public string FKClientPesel { get; set; }
        public string FKAccount_Number { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
