//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanksDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountLogin { get; set; }
        public string AccountPassword { get; set; }
        public string FK_OwnerPesel { get; set; }
        public decimal Cash { get; set; }
    }
}
