//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanksDll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanksEntities : DbContext
    {
        public BanksEntities()
            : base("name=BanksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
